behaves:
    behave:
        available-change: lamp
        device: lampada-one
        data-environment:
            - when time > 22  then environment.light = False
        data-device:
            - when babymonitor.noise == true then environment.light = True

    behave:
        available-change: air-conditioning
        device: air-conditioning-one
        data-environment:
            - while time > 22 then environment.temperatue.set(0.2)
