behaves:
    behave:
        change-environment: lamp
        device: lampada-one
        data-environment:
            - when hours > 22 then environment.light = False
        data-device:
            - when babymonitor.noise == true then environment.light = True

    behave:
        change-environment: air-conditioning
        device: lampada-two
        data-environment:
            - while hours > 22 then environment.temperatue.set(0.2)
    