devices:
    - device:
        name: Geladeira
        description: Geladeira inteligente.
        internal-state:
            - qty_food: nat, 20
            - temperature: termic, 3.25
        sensors:
            - temperature
        actuators:
            - alarm: noise
        environment: Cozinha
        image: fridge.png

    - device:
        name: Microondas
        description: Microondas inteligente.
        internal-state:
            - weight_food: weight, 200.g
            - temperature: termic, 80.25
        sensors:
            - temperature
            - noise
            - light
        actuators:
            - alarm: noise
        attributes:
            - food-weight: float
        environment: Escritorio
        image: microwave.png

    - device:
        name: Lampada
        description: Lampada inteligente.
        internal-state:
            - on_state: bool, False
        sensors:
            - temperature
            - noise
            - light
            - proximity
        actuators:
            - switch: light
        environment: Banheiro
        image: lightbulb.png

    - device:
        name: Torradeira
        internal-state:
            - ready_food: bool, False
            - temperature: termic, 15.25
        description: Torradeira inteligente.
        sensors:
            - temperature
        environment: Banheiro
        image: toaster.png

    - device:
        name: Televisao
        description: Televisao inteligente.
        sensors:
            - light
        environment: Escritorio
        image: television.png

    - device:
        name: Ar condicionado
        internal-state:
            - dirty_filter: bool, False
        description: Ar condicionado inteligente.
        sensors:
            - temperature
            - light
        actuators:
            - alarm: noise
        environment: Cozinha
        image: air-conditioner.png

    - device:
        name: Ventilador
        internal-state:
            - dirty_filter: bool, False
        description: Ventilador inteligente.
        sensors:
            - temperature
            - noise
            - light
        environment: Cozinha
        image: fan.png

    - device:
        name: Relogio
        description: Relogio inteligente.
        sensors:
            - noise
        environment: Cozinha
        image: clock.png

    - device:
        name: Fogao
        description: Fogao inteligente.
        sensors:
            - temperature
            - noise
            - light
        environment: Cozinha
        image: stove.png

    - device:
        name: Estante de livros
        description: Estante de livros inteligente.
        internal-state:
            - weight_books: weight, 2.0kg
            - qty_book: nat, 5
        sensors:
            - temperature
        environment: Escritorio
        image: bookshelf.png

    - device:
        name: Guarda roupa
        description: Guarda roupa inteligente.
        internal-state:
            - qty_clothes: nat, 15
        sensors:
            - temperature
            - light
        environment: Cozinha
        image: wardrobe.png
