people:
    - person:
        name: Pedro
        environment: Cozinha
        image: father.png

    - person:
        name: Sara
        environment: Escritorio
        image: mother.png

    - person:
        name: Matheus
        environment: Quarto
        image: boy.png


